version: '3.2'
services:
  bs4:
    build:
      context: "bs4"
      dockerfile: Dockerfile
    image: python-scraping/bs4
    container_name: python-scraping-bs4
    volumes:
      - ./bs4:/app
    ports:
      - "5678:5678"
    command: "python -X frozen_modules=off -m debugpy --wait-for-client --listen 0.0.0.0:5678 ./main.py"
  playwright:
    build:
      context: "playwright"
      dockerfile: Dockerfile
    image: python-scraping/playwright
    container_name: python-scraping-playwright
    volumes:
      - ./playwright:/app
    ports:
      - "5678:5678"
    command: "python -X frozen_modules=off -m debugpy --wait-for-client --listen 0.0.0.0:5678 ./main.py"
  scrapy:
    build:
      context: "scrapy"
      dockerfile: Dockerfile
    image: python-scraping/scrapy
    container_name: python-scraping-scrapy
    volumes:
      - ./scrapy:/app
    ports:
      - "5678:5678"
    command: "python -X frozen_modules=off -m debugpy --wait-for-client --listen 0.0.0.0:5678 ./main.py"